### ISSUE TITLE
Get Involved - Page

### ISSUE THREAD

**Issue by bazmurphy** [ShayanMahnam/lentegeur-hospital-facility-board#18]
## Story

- **As a** person who wants to donate to the organisation
- **I Want** be able to view donation preamble/information, be linked to an external site for donations, and see the organisation bank account information
- **So That** I can **Donate** financially to the organisation.
---
- **As a** person who wants to give their time to volunteer
- **I Want** be able to visit the Get Involved page and see a Volunteer section
- **So That** I can register to **Volunteer** with the organisation
---

### Acceptance Criteria

- Display Get Involved Page Title
- Display Get Involved Paragraph
- Display a Donate Section
- Display Donate Sub Title
- Display Donate Paragraph
- Display Link to external Donation service platform
- Display organisation bank account information
- Display a Volunteer Section
- Display Volunteer Sub Title
- Display Volunteer Banner Image
- Display Volunteer Paragraph
- Display Volunteer Form with: Sub Title, First Name, Last Name, Email, Phone Number Inputs, Submit Button
- Be styled Mobile First with a Desktop Media Query

## Implementation Notes

1. Should follow a React componentisation philsophy

## Links

Figma Wireframes: [here](https://www.figma.com/file/sQ1wwbSRZ6yRu2pq1Tvyzq/Lentegeur-Hospital-Facility-Board---Wireframes?type=design&t=i9FF8VdoEiFzp3xX-0)

## Checklist:

- [x] I have defined the user story
- [x] I have defined some acceptance criteria
- [x] I have included any implementation notes
- [x] I have included all relevant links

**Comment by tiritaki** [comment]
Hi @bazmurphy I think we can add additional box in Volunteer form. What do you think? Should we ask @VitalinaKuzmenko to amend wireframe for this?


![Image](https://github.com/ShayanMahnam/lentegeur-hospital-facility-board/assets/12444326/7c2f4410-0cf2-487b-b249-73afdded12db)

**Comment by tiritaki** [comment]
Hi @bazmurphy 

Can you pls add below content in Donate section.

Thank you for your willingness to donate to the Lentegeur Psychiatric Hospital Facility Board. Your financial support will directly impact the lives of all who are facing mental health challenges.


Lentegeur Hospital Facility Board
Bank - FNB
Account Number - 59204188287
Branch Code - 250555
Swift Code - FIRNAJJ



![Image](https://github.com/ShayanMahnam/lentegeur-hospital-facility-board/assets/12444326/c46f39a2-f02e-406d-9ba4-0801cff1c87d)

**Comment by bazmurphy** [comment]
@tiritaki 

Done

Was not sure if the text 
_"Thank you for your willingness to donate to the Lentegeur Psychiatric Hospital Facility Board. Your financial support will directly impact the lives of all who are facing mental health challenges."_ 
should be one p element or two p elements, i went with two.

Please also in future @ me on the Pull Request itself to reference back to [your comment](https://github.com/ShayanMahnam/lentegeur-hospital-facility-board/issues/18#issuecomment-1608998856) on the Issue

**Comment by tiritaki** [comment]
Cool! I think with two will be better.
