### ISSUE TITLE
headless CMS Strapi - Spike Story / Timeboxed Investigation

### ISSUE THREAD

**Issue by bazmurphy** [ShayanMahnam/lentegeur-hospital-facility-board#33]
- We would like the client to be able to add new content to the website upon handover
- We need to investigate how feasible that is in 3 weeks
- Is it unrealistic to build our own custom CMS with Node.js and Express in those 3 weeks(?)
- We have decided to investigate Strapi - the leading open source headless CMS written in JavaScript for Node.js - because it could be plugged in to our existing project and provide the functionality we want
- We will need until X day to complete this Timeboxed Investigation to assess the viability of this approach

**Comment by bazmurphy** [comment]
We need a few of us looking into this^

**Comment by tiritaki** [comment]
I have asked Berenice on content, will see what she can provide.
Seems there are some content for events and services, maybe for about page which should be filtered and updated but I could not find any info for news.

**Comment by ShayanMahnam** [comment]
- Easy peasy installation on localhost
- implement it in starter kit will be painful (maybe having different repo for CMS is our best option for now)
- connected Events and News work smoothly 
- still investigating for other features
