### ISSUE TITLE
Gallery - Page

### ISSUE THREAD

**Issue by VitalinaKuzmenko** [ShayanMahnam/lentegeur-hospital-facility-board#5]
**As A** volunteer/patient/stakeholder 
**I WANT TO** navigate to the gallery page 
**SO THAT** I can view images published by the organisation

### Acceptance Criteria

- [ ] Page should display images in responsive grid tiles
- [ ] It should not display all images on render but user should be able to load more

**Comment by tiritaki** [comment]
Hi @ShayanMahnam 

Could you pls update your images in the gallery
from this folder https://drive.google.com/drive/u/0/folders/1CGpgtG_cI_7CtmjxYs84LuRmLbx5Q8id
I extracted these images from events document Heritage Day at LGH 2022 (1)
Let me know if it is possible for you.
