### ISSUE TITLE
Fix Netlify Routing Redirect

### ISSUE THREAD

**Issue by bazmurphy** [ShayanMahnam/lentegeur-hospital-facility-board#63]
## Story

- **As a** User

- **I Want** to be able to visit the routes eg. /news on Netlify

- **So That** I can visit the specific routes if bookmarked etc.

## Acceptance Criteria

1. Given I am trying to access the site via a route
   - When I type in that route and hit enter
   - Then I am sent to the correct route

## Implementation Notes

Current State:
![image](https://github.com/ShayanMahnam/lentegeur-hospital-facility-board/assets/61154071/49fc15eb-e89d-48ee-94f4-20b5ac49630a)

## Checklist:

- [X] I have defined the user story
- [X] I have defined some acceptance criteria
- [X] I have included any implementation notes
- [X] ~I have included all relevant links~

**Comment by ShayanMahnam** [comment]
~let me do this one~ nothing you did it already :D
